# Generated by Django 3.2.9 on 2021-12-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('shop', models.CharField(default='smoker', max_length=120)),
            ],
        ),
    ]
