# Generated by Django 3.2.9 on 2021-12-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
    ]
