# Generated by Django 3.2.9 on 2021-12-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_shops_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='idx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.CharField(default='smokers', max_length=120),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
