# Generated by Django 3.2.9 on 2021-12-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_rename_user_recommendation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
